# ============================================================
# Single-Stage Build (KHÔNG tối ưu) - để compare
# Image sẽ chứa cả Maven + JDK --> rất nặng (~500MB+)
# ============================================================
FROM maven:3.9-eclipse-temurin-17

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY src ./src
RUN mvn clean package -DskipTests

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "target/student-service-1.0.0.jar"]
